/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import aplicacion.*;
import java.awt.Color;

/**
 *
 * @author slimbbok
 */
public class VprincipalCreacionGradoBestia extends javax.swing.JDialog {
    
    private java.util.List<Asignatura> asignaturas;
    private java.util.List<Asignatura> asignaturasBloqueActual;
    private java.util.List<Bloque> bloques;

    private aplicacion.FachadaAplicacion fa;
    /**
     * Creates new form VprincipalCreacionGradoBestia
     */
    public VprincipalCreacionGradoBestia(java.awt.Frame parent, boolean modal,aplicacion.FachadaAplicacion fa) {
        super(parent,modal);
        initComponents();
        this.fa=fa;
        asignaturas = new java.util.ArrayList();
        asignaturasBloqueActual = new java.util.ArrayList();
        bloques = new java.util.ArrayList();
        for(int i=4;i>0;i--){
            jTabbedPane1.remove(i);
        }
        paso1.setEnabled(false);
        paso2.setEnabled(false);
        paso3.setEnabled(false);
        paso4.setEnabled(false);
        spinnerCreditos.getModel().setValue(6);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barraProgreso = new javax.swing.JProgressBar();
        btnSiguiente = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        paso0 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        paso1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtNombreGrado = new javax.swing.JTextField();
        txtCodigoGrado = new javax.swing.JTextField();
        paso2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtNombreBloque = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        listaBloques = new javax.swing.JList<>();
        jLabel27 = new javax.swing.JLabel();
        btnAnadirBloque = new javax.swing.JButton();
        btnEliminarBloque = new javax.swing.JButton();
        paso3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtCodigoAsignatura = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtNombreAsignatura = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        spinnerCreditos = new javax.swing.JSpinner();
        labelTipo = new javax.swing.JLabel();
        comboboxTipoAsignatura = new javax.swing.JComboBox<>();
        labelCurso = new javax.swing.JLabel();
        comboboxCursoAsignatura = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaAsignaturas = new javax.swing.JList<>();
        jLabel20 = new javax.swing.JLabel();
        btnAnadirAsignatura = new javax.swing.JButton();
        btnEliminarAsignatura = new javax.swing.JButton();
        comboboxBloquesAsignaturas = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        paso4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtConfirmNombreGrado = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtConfirmCodigoGrado = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        confirmacionListaAsignaturas = new javax.swing.JList<>();
        jLabel26 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        confirmacionListaBloques = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnSiguiente.setText("Siguiente");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        btnAtras.setText("Atras");
        btnAtras.setEnabled(false);
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        btnSalir.setText("Volver al menu de administración");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jLabel5.setText("Progreso de creación del grado:");

        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        paso0.setName(""); // NOI18N
        paso0.setPreferredSize(new java.awt.Dimension(781, 350));

        jLabel1.setText("Paso 0 de 4");

        jLabel2.setText("Bienvenido al asistente de creación rápida de un grado!");

        jLabel3.setText("Le advertimos que la la creación de un grado utilizando este método pude");

        jLabel4.setText("generar mas errores que la creación del mismo grado de forma secuencial.");

        javax.swing.GroupLayout paso0Layout = new javax.swing.GroupLayout(paso0);
        paso0.setLayout(paso0Layout);
        paso0Layout.setHorizontalGroup(
            paso0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paso0Layout.createSequentialGroup()
                .addGap(329, 329, 329)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paso0Layout.createSequentialGroup()
                .addContainerGap(134, Short.MAX_VALUE)
                .addGroup(paso0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paso0Layout.createSequentialGroup()
                        .addGroup(paso0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(116, 116, 116))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paso0Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(183, 183, 183))))
        );
        paso0Layout.setVerticalGroup(
            paso0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paso0Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addComponent(jLabel2)
                .addGap(41, 41, 41)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addContainerGap(114, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Paso 0", paso0);

        jLabel6.setText("Paso 1 de 4 : Grado");

        jLabel10.setText("Nombre :");

        jLabel11.setText("Código :");

        txtCodigoGrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoGradoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paso1Layout = new javax.swing.GroupLayout(paso1);
        paso1.setLayout(paso1Layout);
        paso1Layout.setHorizontalGroup(
            paso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paso1Layout.createSequentialGroup()
                .addGroup(paso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paso1Layout.createSequentialGroup()
                        .addGap(330, 330, 330)
                        .addComponent(jLabel6))
                    .addGroup(paso1Layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addGroup(paso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(paso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombreGrado, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCodigoGrado, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(136, Short.MAX_VALUE))
        );
        paso1Layout.setVerticalGroup(
            paso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paso1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel6)
                .addGap(39, 39, 39)
                .addGroup(paso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtNombreGrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(paso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtCodigoGrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(155, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Creación Grado", paso1);

        jLabel7.setText("Paso 2 de 4: Bloque");

        jLabel12.setText("Nombre:");

        jLabel13.setText("Descripción :");

        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        jScrollPane1.setViewportView(txtDescripcion);

        listaBloques.setModel(new ModeloListaBloques());
        jScrollPane4.setViewportView(listaBloques);

        jLabel27.setText("Lista bloques :");

        btnAnadirBloque.setText("Añadir Bloque");
        btnAnadirBloque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnadirBloqueActionPerformed(evt);
            }
        });

        btnEliminarBloque.setText("Eliminar Bloque");
        btnEliminarBloque.setEnabled(false);
        btnEliminarBloque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarBloqueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paso2Layout = new javax.swing.GroupLayout(paso2);
        paso2.setLayout(paso2Layout);
        paso2Layout.setHorizontalGroup(
            paso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paso2Layout.createSequentialGroup()
                .addGroup(paso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paso2Layout.createSequentialGroup()
                        .addGap(329, 329, 329)
                        .addComponent(jLabel7)
                        .addGap(101, 101, 101)
                        .addComponent(jLabel27))
                    .addGroup(paso2Layout.createSequentialGroup()
                        .addGroup(paso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(paso2Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(paso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel12))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(paso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNombreBloque)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paso2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnAnadirBloque)
                                .addGap(54, 54, 54)
                                .addComponent(btnEliminarBloque)))
                        .addGap(79, 79, 79)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        paso2Layout.setVerticalGroup(
            paso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paso2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel7)
                .addGap(35, 35, 35)
                .addGroup(paso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtNombreBloque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(paso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(paso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAnadirBloque)
                    .addComponent(btnEliminarBloque))
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(paso2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Creación Bloque", paso2);

        jLabel8.setText("Paso 3 de 4: Asignaturas");

        jLabel15.setText("Código :");

        jLabel16.setText("Nombre:");

        jLabel17.setText("Créditos :");

        labelTipo.setText("Tipo :");

        comboboxTipoAsignatura.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elija un tipo", "Formación básica", "Obligatoria", "Optativa" }));

        labelCurso.setText("Curso :");

        comboboxCursoAsignatura.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elija un curso", "Primero", "Segundo", "Tercero", "Cuarto", "Quinto", "Sexto" }));

        listaAsignaturas.setModel(new ModeloListaAsignaturas());
        jScrollPane2.setViewportView(listaAsignaturas);

        jLabel20.setText("Lista de Asignaturas :");

        btnAnadirAsignatura.setText("Añadir Asignatura");
        btnAnadirAsignatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnadirAsignaturaActionPerformed(evt);
            }
        });

        btnEliminarAsignatura.setText("Eliminar Asignatura");
        btnEliminarAsignatura.setEnabled(false);
        btnEliminarAsignatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarAsignaturaActionPerformed(evt);
            }
        });

        comboboxBloquesAsignaturas.setMaximumRowCount(300);
        comboboxBloquesAsignaturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboboxBloquesAsignaturasActionPerformed(evt);
            }
        });

        jLabel14.setText("Bloque :");

        javax.swing.GroupLayout paso3Layout = new javax.swing.GroupLayout(paso3);
        paso3.setLayout(paso3Layout);
        paso3Layout.setHorizontalGroup(
            paso3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paso3Layout.createSequentialGroup()
                .addGroup(paso3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(paso3Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(paso3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel15)
                            .addComponent(labelTipo)
                            .addComponent(labelCurso))
                        .addGap(18, 18, 18)
                        .addGroup(paso3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(paso3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(comboboxCursoAsignatura, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(comboboxTipoAsignatura, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(paso3Layout.createSequentialGroup()
                                .addComponent(txtCodigoAsignatura, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(jLabel17)
                                .addGap(18, 18, 18)
                                .addComponent(spinnerCreditos, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(19, 19, 19))
                    .addGroup(paso3Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(btnAnadirAsignatura)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEliminarAsignatura)
                        .addGap(51, 51, 51))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paso3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(paso3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel14))
                        .addGap(18, 18, 18)
                        .addGroup(paso3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombreAsignatura, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboboxBloquesAsignaturas, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(paso3Layout.createSequentialGroup()
                .addGap(328, 328, 328)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel20)
                .addGap(56, 56, 56))
        );
        paso3Layout.setVerticalGroup(
            paso3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paso3Layout.createSequentialGroup()
                .addGroup(paso3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paso3Layout.createSequentialGroup()
                        .addGroup(paso3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(paso3Layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addGroup(paso3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtCodigoAsignatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17)
                                    .addComponent(spinnerCreditos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(paso3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(paso3Layout.createSequentialGroup()
                                    .addGap(16, 16, 16)
                                    .addComponent(jLabel8))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paso3Layout.createSequentialGroup()
                                    .addContainerGap(59, Short.MAX_VALUE)
                                    .addComponent(jLabel15))))
                        .addGap(18, 18, 18)
                        .addGroup(paso3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombreAsignatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addGroup(paso3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(paso3Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(paso3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(comboboxBloquesAsignaturas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(comboboxTipoAsignatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(paso3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(labelCurso)
                                    .addComponent(comboboxCursoAsignatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(paso3Layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(labelTipo)))
                        .addGap(18, 18, 18)
                        .addGroup(paso3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAnadirAsignatura)
                            .addComponent(btnEliminarAsignatura))
                        .addGap(0, 3, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paso3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Creación de Asignaturas", paso3);

        jLabel9.setText("Paso 4 de 4: Confirmación");

        jLabel21.setText("Nombre :");

        jLabel22.setText("Grado :");

        jLabel23.setText("Código :");

        jLabel24.setText("Lista de bloques :");

        confirmacionListaAsignaturas.setModel(new ModeloListaAsignaturas());
        jScrollPane3.setViewportView(confirmacionListaAsignaturas);

        jLabel26.setText("Asignaturas  del bloque:");

        confirmacionListaBloques.setModel(new ModeloListaBloques());
        confirmacionListaBloques.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                confirmacionListaBloquesMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(confirmacionListaBloques);

        javax.swing.GroupLayout paso4Layout = new javax.swing.GroupLayout(paso4);
        paso4.setLayout(paso4Layout);
        paso4Layout.setHorizontalGroup(
            paso4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paso4Layout.createSequentialGroup()
                .addGroup(paso4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paso4Layout.createSequentialGroup()
                        .addGap(340, 340, 340)
                        .addComponent(jLabel9))
                    .addGroup(paso4Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(paso4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(paso4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel22)
                                .addComponent(txtConfirmNombreGrado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(paso4Layout.createSequentialGroup()
                                    .addGap(98, 98, 98)
                                    .addComponent(jLabel21))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paso4Layout.createSequentialGroup()
                                    .addComponent(jLabel23)
                                    .addGap(98, 98, 98)))
                            .addComponent(txtConfirmCodigoGrado, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(paso4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(paso4Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paso4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel24)
                                .addGap(73, 73, 73)))
                        .addGroup(paso4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paso4Layout.createSequentialGroup()
                                .addComponent(jLabel26)
                                .addGap(22, 22, 22)))))
                .addContainerGap())
        );
        paso4Layout.setVerticalGroup(
            paso4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paso4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(paso4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel26)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paso4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(paso4Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtConfirmNombreGrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel23)
                        .addGap(14, 14, 14)
                        .addComponent(txtConfirmCodigoGrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Confirmación", paso4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(btnSalir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSiguiente)
                .addGap(15, 15, 15))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 783, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(barraProgreso, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(275, 275, 275)
                        .addComponent(jLabel5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(barraProgreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSiguiente)
                    .addComponent(btnAtras)
                    .addComponent(btnSalir))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodigoGradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoGradoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoGradoActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        switch(jTabbedPane1.getSelectedIndex()){
            case 0:
                if(!paso1.isEnabled()){
                    jTabbedPane1.add(paso1);
                    paso1.setEnabled(true);
                    jTabbedPane1.setTitleAt(1, "Creación Grado");
                }
                jTabbedPane1.setSelectedIndex(1);
                barraProgreso.setValue(25);
                btnAtras.setEnabled(true);
                break;
            case 1:
                if(!paso2.isEnabled()){
                    jTabbedPane1.add(paso2);
                    paso2.setEnabled(true);
                    jTabbedPane1.setTitleAt(2, "Creación Bloque");
                }
                jTabbedPane1.setSelectedIndex(2);
                barraProgreso.setValue(50);
                break;
            case 2:
                if(!paso3.isEnabled()){
                    jTabbedPane1.add(paso3);
                    paso3.setEnabled(true);
                    jTabbedPane1.setTitleAt(3, "Creación Asignaturas");
                }
                comboboxBloquesAsignaturas.removeAllItems();
                for(Bloque b:bloques) comboboxBloquesAsignaturas.addItem(b.getNombre());
                jTabbedPane1.setSelectedIndex(3);
                barraProgreso.setValue(75);
                break;
            case 3:
                if(!paso4.isEnabled()){
                    jTabbedPane1.add(paso4);
                    paso4.setEnabled(true);
                    jTabbedPane1.setTitleAt(4, "Cornfirmación");
                }
                jTabbedPane1.setSelectedIndex(4);
                barraProgreso.setValue(100);
                txtConfirmNombreGrado.setText(txtNombreGrado.getText());
                txtConfirmCodigoGrado.setText(txtCodigoGrado.getText());
                ((ModeloListaBloques) confirmacionListaBloques.getModel()).setElementos(bloques);
                if(bloques.size()>0){
                    confirmacionListaBloques.setSelectedIndex(0);
                    asignaturasBloqueActual.clear();
                    for(Asignatura a:asignaturas)
                        if(a.getBloque().equals(bloques.get(0).getNombre()))
                            asignaturasBloqueActual.add(a);
                    ((ModeloListaAsignaturas)confirmacionListaAsignaturas.getModel()).setElementos(asignaturasBloqueActual);
                }
                btnSiguiente.setText("Confirmar");
                break;
            case 4:
                Grado gr = new Grado(txtConfirmNombreGrado.getText(), txtConfirmCodigoGrado.getText(), asignaturas);
                if(fa.inserrtarGradoAsistente(gr, bloques));
                    this.dispose();
                break;
        }
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        btnSiguiente.setText("Siguiente");
        switch(jTabbedPane1.getSelectedIndex()){
            case 1:
                btnAtras.setEnabled(false);
                jTabbedPane1.setSelectedIndex(0);
                barraProgreso.setValue(0);
                break;
            case 2:
                jTabbedPane1.setSelectedIndex(jTabbedPane1.getSelectedIndex()-1);
                barraProgreso.setValue(25);
                break;
            case 3:
                jTabbedPane1.setSelectedIndex(jTabbedPane1.getSelectedIndex()-1);
                barraProgreso.setValue(50);
                break;
            case 4:
                jTabbedPane1.setSelectedIndex(jTabbedPane1.getSelectedIndex()-1);
                barraProgreso.setValue(75);
                break;
        }
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        switch(jTabbedPane1.getSelectedIndex()){
            case 0:
                btnSiguiente.setText("Siguiente");
                barraProgreso.setValue(0);
                break;
            case 1:
                btnSiguiente.setText("Siguiente");
                barraProgreso.setValue(25);
                break;
            case 2:
                btnSiguiente.setText("Siguiente");
                barraProgreso.setValue(50);
                break;
            case 3:
                btnSiguiente.setText("Siguiente");
                barraProgreso.setValue(75);
                break;
            case 4:
                btnSiguiente.setText("Confirmar");
                barraProgreso.setValue(100);
                txtConfirmNombreGrado.setText(txtNombreGrado.getText());
                txtConfirmCodigoGrado.setText(txtCodigoGrado.getText());
                ((ModeloListaBloques) confirmacionListaBloques.getModel()).setElementos(bloques);
                if(bloques.size()>=0) confirmacionListaBloques.setSelectedIndex(0);
                ((ModeloListaAsignaturas)confirmacionListaAsignaturas.getModel()).setElementos(asignaturas);
                break;
        }
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void btnAnadirBloqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnadirBloqueActionPerformed
        bloques.add(new Bloque(txtNombreBloque.getText(), txtCodigoGrado.getText(), txtDescripcion.getText()));
        ((ModeloListaBloques) listaBloques.getModel()).setElementos(bloques);
        listaBloques.setSelectedIndex(bloques.size()-1);
        btnEliminarBloque.setEnabled(true);
    }//GEN-LAST:event_btnAnadirBloqueActionPerformed

    private void btnEliminarBloqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarBloqueActionPerformed
        bloques.remove(listaBloques.getSelectedIndex());
        ((ModeloListaBloques) listaBloques.getModel()).setElementos(bloques);
        listaBloques.setSelectedIndex(0);
        if(bloques.size()==0)
            btnEliminarBloque.setEnabled(false);
    }//GEN-LAST:event_btnEliminarBloqueActionPerformed

    private void btnAnadirAsignaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnadirAsignaturaActionPerformed
        if(comboboxTipoAsignatura.getSelectedIndex()!=0){
            labelTipo.setForeground(Color.black);
            if(comboboxCursoAsignatura.getSelectedIndex()!=0){
                labelCurso.setForeground(Color.black);
                Asignatura a = new Asignatura(txtNombreAsignatura.getText(), txtCodigoAsignatura.getText(), bloques.get(comboboxBloquesAsignaturas.getSelectedIndex()).getNombre(), txtCodigoGrado.getText(), ((int) spinnerCreditos.getValue()), ((String) comboboxTipoAsignatura.getSelectedItem()), comboboxCursoAsignatura.getSelectedIndex() , 0);
                asignaturas.add(a);
                asignaturasBloqueActual.add(a);
                ((ModeloListaAsignaturas) listaAsignaturas.getModel()).setElementos(asignaturasBloqueActual);
                if(asignaturasBloqueActual.size()>0)listaAsignaturas.setSelectedIndex(asignaturas.size()-1);
                btnEliminarAsignatura.setEnabled(true);
            }else labelCurso.setForeground(Color.red);
            
        }else labelTipo.setForeground(Color.red);
    }//GEN-LAST:event_btnAnadirAsignaturaActionPerformed

    private void comboboxBloquesAsignaturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboboxBloquesAsignaturasActionPerformed
        asignaturasBloqueActual.clear();
        for(Asignatura a:asignaturas){
            if(a.getBloque().equals(comboboxBloquesAsignaturas.getSelectedItem()))
                asignaturasBloqueActual.add(a);
        }
        ((ModeloListaAsignaturas) listaAsignaturas.getModel()).setElementos(asignaturasBloqueActual);
        if(asignaturasBloqueActual.size()>0) listaAsignaturas.setSelectedIndex(0);
    }//GEN-LAST:event_comboboxBloquesAsignaturasActionPerformed

    private void btnEliminarAsignaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarAsignaturaActionPerformed
        Asignatura a = asignaturasBloqueActual.get(listaAsignaturas.getSelectedIndex());
        asignaturas.remove(a);
        asignaturasBloqueActual.remove(listaAsignaturas.getSelectedIndex());
        ((ModeloListaAsignaturas) listaAsignaturas.getModel()).setElementos(asignaturasBloqueActual);
        if(asignaturasBloqueActual.size()>0) listaAsignaturas.setSelectedIndex(0);
        else if(asignaturasBloqueActual.size()==0) btnEliminarAsignatura.setEnabled(false);
    }//GEN-LAST:event_btnEliminarAsignaturaActionPerformed

    private void confirmacionListaBloquesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmacionListaBloquesMouseClicked
        asignaturasBloqueActual.clear();
        for(Asignatura a:asignaturas)
            if(a.getBloque().equals(bloques.get(confirmacionListaBloques.getSelectedIndex()).getNombre()))
                asignaturasBloqueActual.add(a);
        ((ModeloListaAsignaturas) confirmacionListaAsignaturas.getModel()).setElementos(asignaturasBloqueActual);
    }//GEN-LAST:event_confirmacionListaBloquesMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar barraProgreso;
    private javax.swing.JButton btnAnadirAsignatura;
    private javax.swing.JButton btnAnadirBloque;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnEliminarAsignatura;
    private javax.swing.JButton btnEliminarBloque;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JComboBox<String> comboboxBloquesAsignaturas;
    private javax.swing.JComboBox<String> comboboxCursoAsignatura;
    private javax.swing.JComboBox<String> comboboxTipoAsignatura;
    private javax.swing.JList<String> confirmacionListaAsignaturas;
    private javax.swing.JList<String> confirmacionListaBloques;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel labelCurso;
    private javax.swing.JLabel labelTipo;
    private javax.swing.JList<String> listaAsignaturas;
    private javax.swing.JList<String> listaBloques;
    private javax.swing.JPanel paso0;
    private javax.swing.JPanel paso1;
    private javax.swing.JPanel paso2;
    private javax.swing.JPanel paso3;
    private javax.swing.JPanel paso4;
    private javax.swing.JSpinner spinnerCreditos;
    private javax.swing.JTextField txtCodigoAsignatura;
    private javax.swing.JTextField txtCodigoGrado;
    private javax.swing.JTextField txtConfirmCodigoGrado;
    private javax.swing.JTextField txtConfirmNombreGrado;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtNombreAsignatura;
    private javax.swing.JTextField txtNombreBloque;
    private javax.swing.JTextField txtNombreGrado;
    // End of variables declaration//GEN-END:variables
}
